# Generated by Django 4.1 on 2022-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gstno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('company', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('total_amount', models.CharField(max_length=200)),
                ('cgst', models.CharField(max_length=200)),
                ('sgst', models.CharField(max_length=200)),
                ('tgst', models.CharField(max_length=200)),
                ('cgst_amount', models.CharField(max_length=200)),
                ('sgst_amount', models.CharField(max_length=200)),
                ('tgst_amount', models.CharField(max_length=200)),
                ('grand_total', models.CharField(max_length=200)),
                ('word_total', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_company', models.CharField(max_length=500)),
                ('to_company', models.CharField(max_length=500)),
                ('vehical', models.CharField(max_length=200)),
                ('trip', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('Report', models.ManyToManyField(to='sant.report')),
            ],
        ),
    ]
