# Generated by Django 4.1 on 2022-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='laborer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lamount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lrate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ltrip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lvno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
